### ISSUE TITLE
Malware report from Bitdefender

### ISSUE THREAD

**Issue by hugo4715** [Epidocs/epita.it#29] opened 2019-09-29 19:41 UTC
Bitdefender reports epita.it as an infected website.
![image](https://user-images.githubusercontent.com/10290315/65838281-d89ab200-e301-11e9-879d-3d9c69a0b34a.png)

**Comment by matiboux** [comment] 2019-09-29 20:17
Hi, I am aware of this problem.

Sadly, that's not a problem I can fix directly..
The issue actually comes from EPITA services not being served over HTTPS:
- Intracom
- Odyssee
- Chronos

When opening the developer console on EPITA.it, we get these warnings:

```
Mixed Content:
  The page at 'https://epita.it/' was loaded over HTTPS,
  but requested an insecure image 'http://intracom.epita.fr/assets/img/intracomLogo.png'.
  This content should also be served over HTTPS.
Mixed Content:
  The page at 'https://epita.it/' was loaded over HTTPS,
  but requested an insecure image 'http://odyssee.epita.fr/img/design/nv/logo_epita.jpg'.
  This content should also be served over HTTPS.
Mixed Content:
  The page at 'https://epita.it/' was loaded over HTTPS,
  but requested an insecure image 'http://chronos.epita.net/ade/img/bgEnterprise.gif'.
  This content should also be served over HTTPS.
```

While the issue is not addressed by the people in charge of these services,
I should probably host the images elsewhere.

**Comment by matiboux** [comment] 2019-09-29 20:21
Images will be hosted over HTTPS on https://cdn.matiboux.com/images/epita.it/ until the issue is fixed on the services themselves.

**Closed** 2019-09-29 20:26 UTC
